### ISSUE TITLE
error on index.js

### ISSUE THREAD

**Issue by dipenpatel235** [lpinca/binb#26]
i am using: centos 7 64 bit.
 node --version   v0.10.29

when i start service then get below error
 node app.js

/root/binb/node_modules/primus/index.js:177
    const sandbox = Object.keys(global).reduce((acc, key) => {
    ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/binb/lib/sparks.js:11:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by lpinca** [comment]
You have to use Node.js >= 4

**Comment by dipenpatel235** [comment]
i have blow nodejs version. so please check that

nodejs-6.9.4

**Comment by lpinca** [comment]
In your previous comment you said that you were using node 0.10.29.
If you are now using node 6.9.4 it should work fine.
