### ISSUE TITLE
room.artistName.toLowerCase

### ISSUE THREAD

**Issue by dipenpatel235** [lpinca/binb#28]
Hello..
i have modified room name and after that getting below issue when i am starting to service.
so where is error ?
can u please help me ?

/root/binb/lib/rooms.js:541
      room.artist = room.artistName.toLowerCase();
                                   ^

TypeError: Cannot read property 'toLowerCase' of null
    at Command.callback (/root/binb/lib/rooms.js:541:36)
    at normal_reply (/root/binb/node_modules/redis/index.js:721:21)
    at RedisClient.return_reply (/root/binb/node_modules/redis/index.js:819:9)
    at JavascriptRedisParser.returnReply (/root/binb/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/root/binb/node_modules/redis-parser/lib/parser.js:560:12)
    at Socket.<anonymous> (/root/binb/node_modules/redis/index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)

**Comment by lpinca** [comment]
@dipenpatel235 this issue tracker is for **bugs**, not for support questions.

The error means that the [query](https://github.com/lpinca/binb/blob/da4f7495ee81b7c683e926d15d4266e5cb347e8c/lib/rooms.js#L528-L535) to the db failed.
Why? Probably because data hasn't been loaded correctly but it isn't an issue in this code.

**Comment by dipenpatel235** [comment]
okey..thanks
